import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateDashboardReport = ({
  user,
  stats,
  recentTickets = [],
  priorityData = [],
  agents = [],
  chartData = [],
  slaAlerts = [],
  shiftStats = [],
  teamBreakdown = [],
}) => {
  const doc = new jsPDF();

  // -----------------------------
  // Header
  // -----------------------------
  doc.setFontSize(22);
  doc.setTextColor(31, 78, 121);
  doc.text("VDesk Helpdesk Dashboard Report", 14, 20);

  doc.setFontSize(11);
  doc.setTextColor(80);

  doc.text(
    `Generated By : ${user?.name || "Administrator"}`,
    14,
    30
  );

  doc.text(
    `Role : ${user?.role || "Admin"}`,
    14,
    37
  );

  doc.text(
    `Generated On : ${new Date().toLocaleString()}`,
    14,
    44
  );

  doc.line(14, 50, 195, 50);

  // -----------------------------
  // Dashboard Summary
  // -----------------------------

  doc.setFontSize(16);
  doc.setTextColor(31, 78, 121);
  doc.text("Dashboard Summary", 14, 60);

  autoTable(doc, {
    startY: 66,
    theme: "grid",

    head: [["Metric", "Value"]],

    body: [
      ["Total Tickets", stats?.total || 0],
      ["Pending Tickets", stats?.pending || 0],
      ["Resolved Tickets", stats?.resolved || 0],
      ["SLA Breached", stats?.slaBreached || 0],
      ["Average Resolution Time", stats?.avgResolutionTime || "0 hrs"],
    ],
  });

  // -----------------------------
  // Recent Tickets
  // -----------------------------

  doc.addPage();

  doc.setFontSize(16);
  doc.setTextColor(31, 78, 121);
  doc.text("Recent Tickets", 14, 20);

  autoTable(doc, {
    startY: 28,

    head: [[
      "Ticket ID",
      "Title",
      "Priority",
      "Status",
      "Employee",
    ]],

    body:
      recentTickets.length > 0
        ? recentTickets.map((ticket) => [
            ticket.ticketId,
            ticket.title,
            ticket.priority,
            ticket.status,
            ticket.createdBy?.name || "-",
          ])
        : [["-", "-", "-", "-", "-"]],
  });

  // -----------------------------
  // Priority Breakdown
  // -----------------------------

  doc.addPage();

  doc.setFontSize(16);
  doc.text("Priority Breakdown", 14, 20);

  autoTable(doc, {
    startY: 28,

    head: [["Priority", "Count"]],

    body:
      priorityData.length > 0
        ? priorityData.map((item) => [
            item._id,
            item.count,
          ])
        : [["No Data", "0"]],
  });

  // -----------------------------
  // Team Breakdown
  // -----------------------------

  doc.addPage();

  doc.setFontSize(16);
  doc.text("Team Breakdown", 14, 20);

  autoTable(doc, {
    startY: 28,

    head: [["Team", "Tickets"]],

    body:
      teamBreakdown.length > 0
        ? teamBreakdown.map((team) => [
            team._id,
            team.count,
          ])
        : [["No Data", "0"]],
  });

  // -----------------------------
  // Shift Statistics
  // -----------------------------

  doc.addPage();

  doc.setFontSize(16);
  doc.text("Shift Statistics", 14, 20);

  autoTable(doc, {
    startY: 28,

    head: [["Shift", "Tickets"]],

    body:
      shiftStats.length > 0
        ? shiftStats.map((shift) => [
            shift._id,
            shift.count,
          ])
        : [["No Data", "0"]],
  });

  // -----------------------------
  // SLA Alerts
  // -----------------------------

  doc.addPage();

  doc.setFontSize(16);
  doc.text("SLA Alerts", 14, 20);

  autoTable(doc, {
    startY: 28,

    head: [["Ticket", "Reason"]],

    body:
      slaAlerts.length > 0
        ? slaAlerts.map((sla) => [
            sla.ticketId,
            sla.reason || "SLA Breached",
          ])
        : [["No Alerts", "-"]],
  });

  // -----------------------------
  // Live Agents
  // -----------------------------

  doc.addPage();

  doc.setFontSize(16);
  doc.text("Support Agent Workload", 14, 20);

  autoTable(doc, {
    startY: 28,

    head: [[
      "Agent",
      "Status",
      "Workload",
    ]],

    body:
      agents.length > 0
        ? agents.map((agent) => [
            agent.name,
            agent.liveStatus,
            agent.currentWorkload,
          ])
        : [["No Agents", "-", "-"]],
  });

  // -----------------------------
  // Footer
  // -----------------------------

  const totalPages = doc.internal.getNumberOfPages();

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    doc.setFontSize(10);

    doc.setTextColor(120);

    doc.text(
      "Generated by VDesk Helpdesk Management System",
      14,
      287
    );

    doc.text(
      `Page ${i} of ${totalPages}`,
      170,
      287
    );
  }

  doc.save("VDesk_Dashboard_Report.pdf");
};